spring.application.name=spring-shell
file.parser=csv
data.path.csv.tariff=data/Tariff.csv
data.path.csv.account=data/account.csv

data.path.json.tariff=data/Tariff.json
data.path.json.account=data/account.json